export const documentosData = {
  hero: {
    eyebrow: 'GESTION DOCUMENTAL CENTRALIZADA',
    title: ['REPOSITORIO DE', 'RECURSOS DIGITALES'],
    description:
      'Descargue formularios de kardex, reglamentos vigentes, mallas curriculares y resoluciones oficiales emitidas por la Carrera de Estadistica.',
  },
  documentos: [
    {
      id: 'doc-001',
      titulo: 'Formulario de Solicitud de Record Academico (Kardex)',
      categoria: 'Formularios y Tramites',
      formato: 'pdf',
      peso: '1.2 MB',
      ultimaActualizacion: '2026-01-15',
      urlArchivo: '#',
    },
    {
      id: 'doc-002',
      titulo: 'Plantilla de Carta para Solicitud de Tutor de Tesis',
      categoria: 'Formularios y Tramites',
      formato: 'docx',
      peso: '250 KB',
      ultimaActualizacion: '2025-03-10',
      urlArchivo: '#',
    },
    {
      id: 'doc-003',
      titulo: 'Reglamento General de Pasantias e Interaccion Social',
      categoria: 'Normativa y Reglamentos',
      formato: 'pdf',
      peso: '3.5 MB',
      ultimaActualizacion: '2025-11-20',
      urlArchivo: '#',
    },
    {
      id: 'doc-004',
      titulo: 'Estatuto Organico de la Universidad Mayor de San Andres',
      categoria: 'Normativa y Reglamentos',
      formato: 'pdf',
      peso: '8.1 MB',
      ultimaActualizacion: '2024-05-05',
      urlArchivo: '#',
    },
    {
      id: 'doc-005',
      titulo: 'Calendario Academico Gestion 2026 - Carrera de Estadistica',
      categoria: 'Gestion Academica',
      formato: 'pdf',
      peso: '1.5 MB',
      ultimaActualizacion: '2026-01-02',
      urlArchivo: '#',
    },
    {
      id: 'doc-006',
      titulo: 'Malla Curricular Vigente (Plan de Estudios 2022)',
      categoria: 'Gestion Academica',
      formato: 'pdf',
      peso: '2.4 MB',
      ultimaActualizacion: '2022-08-12',
      urlArchivo: '#',
    },
    {
      id: 'doc-007',
      titulo: 'Resolucion HCC 045/2025: Designacion de Auxiliares',
      categoria: 'Resoluciones (HCC / HCF)',
      formato: 'pdf',
      peso: '1.1 MB',
      ultimaActualizacion: '2025-12-15',
      urlArchivo: '#',
    },
    {
      id: 'doc-008',
      titulo: 'Resolucion HCF 112/2024: Homologacion de Cursos de Temporada',
      categoria: 'Resoluciones (HCC / HCF)',
      formato: 'pdf',
      peso: '1.8 MB',
      ultimaActualizacion: '2024-10-20',
      urlArchivo: '#',
    },
  ],
  categorias: [
    { id: 'cat1', name: 'Formularios y Tramites', icon: 'ClipboardList', color: 'text-blue-600' },
    { id: 'cat2', name: 'Normativa y Reglamentos', icon: 'Scale', color: 'text-purple-600' },
    { id: 'cat3', name: 'Gestion Academica', icon: 'BookText', color: 'text-emerald-600' },
    { id: 'cat4', name: 'Resoluciones (HCC / HCF)', icon: 'FileSignature', color: 'text-orange-600' },
  ],
  kardex: {
    phone: '2612824 – Int. 104',
    email: 'kardex@estadistica.umsa.bo',
    hours: '09:00 - 12:00 | 15:00 - 18:00',
  },
  sello: {
    title: 'Sello de Validez Institucional',
    description:
      'Todos los formularios y normativas descargados de este portal son las versiones oficiales aprobadas por el Honorable Consejo de Carrera para la gestion 2026. Evite el uso de documentos obsoletos.',
    badges: ['VERIFICACION 2026', 'FIRMA DIGITAL H.C.C.'],
  },
};
