export const AUTORES = [
  { id: "aut-001", tipo: "persona", nombre_completo: "Wackerly, Dennis D.", letra_inicial: "W", especialidad: "Estadística Matemática", afiliacion: "Universidad de Florida" },
  { id: "aut-002", tipo: "persona", nombre_completo: "Walpole, Ronald E.", letra_inicial: "W", especialidad: "Probabilidad e Inferencia", afiliacion: "Roanoke College" },
  { id: "aut-003", tipo: "persona", nombre_completo: "Montgomery, Douglas C.", letra_inicial: "M", especialidad: "Diseño de Experimentos", afiliacion: "Arizona State University" },
  { id: "aut-004", tipo: "persona", nombre_completo: "Devore, Jay L.", letra_inicial: "D", especialidad: "Ingeniería y Ciencias", afiliacion: "California Poly. State Univ." },
  { id: "aut-005", tipo: "persona", nombre_completo: "Cochran, William G.", letra_inicial: "C", especialidad: "Técnicas de Muestreo", afiliacion: "Harvard University" },
  { id: "aut-006", tipo: "persona", nombre_completo: "Mendenhall, William", letra_inicial: "M", especialidad: "Estadística Matemática", afiliacion: "Universidad de Florida" },
  { id: "aut-007", tipo: "institucion", nombre_completo: "Instituto Nacional de Estadística (INE)", letra_inicial: "I", especialidad: "Censos y Encuestas Oficiales", afiliacion: "Estado Plurinacional de Bolivia" },
  { id: "aut-008", tipo: "persona", nombre_completo: "Coa Clemente, Ramiro", letra_inicial: "C", especialidad: "Demografía y Estadística Social", afiliacion: "IETA - UMSA" },
  { id: "aut-009", tipo: "institucion", nombre_completo: "Banco Central de Bolivia (BCB)", letra_inicial: "B", especialidad: "Indicadores Macroeconómicos", afiliacion: "Estado Plurinacional de Bolivia" },
];

export const LIBROS = [
  { id: "lib-001", titulo: "Estadística matemática con aplicaciones", isbn: "978-9706861314", id_autor: "aut-001", categoria: "Inferencia", tipo_material: "Texto impreso", editor: "Cengage Learning, 7ma Edición", fecha: "2010", codigo: "519.5 W115e", descripcion: "845 páginas; 24 cm.", temas: ["Estadística Matemática", "Probabilidad", "Inferencia"], portada: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-002", titulo: "Probabilidad y estadística para ingeniería y ciencias", isbn: "978-6073214179", id_autor: "aut-002", categoria: "Probabilidad", tipo_material: "Texto impreso", editor: "Pearson Educación, 9na Edición", fecha: "2012", codigo: "519.2 W218p", descripcion: "792 páginas; 25 cm.", temas: ["Ingeniería", "Probabilidad", "Estadística Aplicada"], portada: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-003", titulo: "Diseño y análisis de experimentos", isbn: "978-9681861560", id_autor: "aut-003", categoria: "Experimentación", tipo_material: "Libro Digital", editor: "Limusa Wiley, 2da Edición", fecha: "2004", codigo: "519.53 M787d", descripcion: "Recurso electrónico; PDF.", temas: ["Diseño experimental", "Análisis de varianza"], portada: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-004", titulo: "Probabilidad y estadística para ciencias e ingeniería", isbn: "978-6074816198", id_autor: "aut-004", categoria: "Probabilidad", tipo_material: "Texto impreso", editor: "Cengage Learning, 8va Edición", fecha: "2012", codigo: "519.5 D498p", descripcion: "740 páginas; 26 cm.", temas: ["Estadística para ciencias", "Modelos estocásticos"], portada: "https://images.unsplash.com/photo-1512820200525-8308d1a425a9?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-005", titulo: "Técnicas de muestreo", isbn: "978-9682601523", id_autor: "aut-005", categoria: "Muestreo", tipo_material: "Texto impreso", editor: "CECSA", fecha: "1998", codigo: "519.52 C663t", descripcion: "513 páginas; 23 cm.", temas: ["Muestreo estadístico", "Encuestas", "Muestreo estratificado"], portada: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-006", titulo: "Introducción a la Probabilidad y Estadística", isbn: "978-6074813357", id_autor: "aut-006", categoria: "Probabilidad", tipo_material: "Texto impreso", editor: "Cengage Learning, 13va Edición", fecha: "2010", codigo: "519.2 M537i", descripcion: "716 páginas; 27 cm.", temas: ["Introducción a la estadística", "Inferencia básica"], portada: "https://images.unsplash.com/photo-1555448248-2571daf6344b?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-007", titulo: "Resultados del Censo de Población y Vivienda 2012", isbn: "S/N", id_autor: "aut-007", categoria: "Demografía", tipo_material: "Informe Técnico", editor: "INE Bolivia", fecha: "2013", codigo: "318.4 B689r", descripcion: "200 páginas; Tablas estadísticas.", temas: ["Censos", "Bolivia", "Población"], portada: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-008", titulo: "Desigualdades en los ingresos de adultos mayores bolivianos", isbn: "Revista Varianza", id_autor: "aut-008", categoria: "Social", tipo_material: "Artículo Científico", editor: "IETA - UMSA", fecha: "2024", codigo: "305.26 C652d", descripcion: "Edición 24; 22 páginas.", temas: ["Adultos mayores", "Ingresos", "Regresión Cuantil"], portada: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-009", titulo: "Dinámica demográfica post-COVID en áreas periurbanas", isbn: "Revista Varianza", id_autor: "aut-008", categoria: "Demografía", tipo_material: "Artículo Científico", editor: "IETA - UMSA", fecha: "2023", codigo: "304.6 C652d", descripcion: "Edición 22; 18 páginas.", temas: ["Demografía", "COVID-19", "Periurbano"], portada: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-010", titulo: "Boletín Estadístico Macroeconómico 2023", isbn: "S/N", id_autor: "aut-009", categoria: "Econometría", tipo_material: "Informe Técnico", editor: "BCB", fecha: "2023", codigo: "330.9 B689m", descripcion: "145 páginas; Gráficos.", temas: ["Macroeconomía", "Bolivia", "Inflación"], portada: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-011", titulo: "Análisis de Series de Tiempo aplicadas a la Economía", isbn: "978-8420542318", id_autor: "aut-003", categoria: "Series de Tiempo", tipo_material: "Texto impreso", editor: "Pearson", fecha: "2015", codigo: "519.55 M787s", descripcion: "320 páginas.", temas: ["Series temporales", "Predicción"], portada: "https://images.unsplash.com/photo-1551288049-bbbda5366392?auto=format&fit=crop&q=80&w=400" },
  { id: "lib-012", titulo: "Machine Learning: Un enfoque Estadístico", isbn: "978-1456543210", id_autor: "aut-004", categoria: "Machine Learning", tipo_material: "Libro Digital", editor: "Springer", fecha: "2021", codigo: "006.31 D498m", descripcion: "PDF Interactivo.", temas: ["Inteligencia Artificial", "Modelos estadísticos"], portada: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400" },
];

export const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

export const buildLibraryUrl = (titulo) => {
  let baseUrl = "https://bibliotecas.umsa.bo/cgi-bin/koha/opac-search.pl?q=";
  return baseUrl + encodeURIComponent(`ti:${titulo}`);
};
